### PR TITLE
Add 'wordBreak' option to prevent cutting words

### PR DESCRIPTION
**Pull request by alejandroiglesias**
Ideally, this would be set as an attribute so that it can be controlled on a per-instance basis, but it exceeds what I can do now and this seems good enough for now.

### CODE REVIEW

**Comment by AndyDyer** [comment]
I agree with the idea, but why not just add the ability to pass in what word-wrap you want 
`options = {...options, textOverflow: 'ellipsis', wordBreak: 'normal'};`
` word-break: ${options.wordBreak};`

https://github.com/Frondor/vue-line-clamp/pull/28
@alejandroiglesias

**Comment by alejandroiglesias** [comment]
@AndyDyer I'm okay with whatever method allows me to achieve `word-break: break-word`.

**Comment by Frondor** [comment]
Thanks both for your contributions!

At the moment we are not setting any `word-break` by default... What stops you from selecting the element and applying the css yourself? I don't believe `word-break` goes with the `line-break` idea, neither its `vue-line-clamp` responsibility to set it.

**Comment by AndyDyer** [comment]
@Frondor  Totally could set it by ourselves, but the fact you are setting word-break to its non default value leads me to believe that their is an inherent link between word-break and line-break.  

In fact the use case that made me do this was that I needed word-break to be its default value and was surprised that you were changing it

**Comment by alejandroiglesias** [comment]
@Frondor vue-line-clamp [*does* set `word-break`](https://github.com/Frondor/vue-line-clamp/blob/master/src/index.js#L51).

**Comment by franciscolourenco** [comment]
Why is `word-break: break-all` on by default?

**Comment by Frondor** [comment]
For some reason I missed that line, and we are indeed setting `word-break` to a hardcoded default.

I'm closing this in favor of #28 for an extended config.
Thank you both, and  sorry for the delay.

**Pull request closed without merging**
