### PR TITLE
transpile to ES5

### PR DESCRIPTION
**Pull request by zevdg**
I also added the build step as a "prepublishOnly" npm script so it will auto-build on npm publish

### CODE REVIEW

**Comment by Frondor** [comment]
Thank you for this! 
But why not just use the config file?
Like https://github.com/ElemeFE/vue-infinite-scroll/blob/master/rollup.config.js does, some dependencies are not really needed. Try it
```js
//   "devDependencies"
 {
    "babel-preset-es2015-rollup": "^3.0.0", // new
    "jest": "^22.1.4",
    "rollup": "^0.50.0",
    "rollup-plugin-babel": "^3.0.3",
    "rollup-plugin-commonjs": "^8.2.6",
    "rollup-plugin-node-resolve": "^3.0.0",
    "watch-http-server": "^0.7.6"
  }
```
And the config file just needs to know the preset
```js
    plugins: [
      resolve(),
      commonjs(),
      babel({
        exclude: 'node_modules/**',
        presets: ['es2015-rollup']
      })
    ]
```
There's no need of a `.babelrc` file or any other rollup plugin actually

**Comment by zevdg** [comment]
No good reason.  I just googled "Babel and Rollup" and found https://github.com/rollup/rollup-plugin-babel/blob/master/README.md and followed those instructions.

I don't have any preference on how Babel is configured as long as the UMD ends up as ES5.

**Comment by zevdg** [comment]
For the record, the readme I linked to says

> Babel will respect .babelrc files – this is generally the best place to put your configuration.

And also

> Since Babel 6.3 it's possible to deactivate module transformation with `"modules": false`. So there is no need to use the old workaround with `babel-preset-es2015-rollup`

So the changes you're suggesting seem to go against the recommendations of the readme.

**Comment by zevdg** [comment]
Oh, and lastly, `babel-preset-es2015-rollup` is based on http://babeljs.io/docs/plugins/preset-es2015/ and according to those docs,

> This is deprecated. If you want to stay up to date, use the env preset

**Comment by Frondor** [comment]
Cool, I'm convinced!

Now I wonder, since `babel-core`, `babel-plugin-external-helpers` and `babel-preset-env` are dependencies of `rollup-plugin-babel`, shouldn't we ignore those?

**Comment by zevdg** [comment]
nah.  They're **dev** dependencies https://github.com/rollup/rollup-plugin-babel/blob/master/package.json#L43-L47, so they don't get automatically installed when we install `rollup-plugin-babel`.  They have to be added separately.

**Comment by Frondor** [comment]
Thank you!

**Pull request merged**
